// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	cfg "github.com/andrskom/gowfnet/cfg"
	mock "github.com/stretchr/testify/mock"
)

// CfgInterface is an autogenerated mock type for the Interface type
type CfgInterface struct {
	mock.Mock
}

// GetFinish provides a mock function with given fields:
func (_m *CfgInterface) GetFinish() cfg.IDGetter {
	ret := _m.Called()

	var r0 cfg.IDGetter
	if rf, ok := ret.Get(0).(func() cfg.IDGetter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cfg.IDGetter)
		}
	}

	return r0
}

// GetPlaces provides a mock function with given fields:
func (_m *CfgInterface) GetPlaces() []cfg.IDGetter {
	ret := _m.Called()

	var r0 []cfg.IDGetter
	if rf, ok := ret.Get(0).(func() []cfg.IDGetter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cfg.IDGetter)
		}
	}

	return r0
}

// GetStart provides a mock function with given fields:
func (_m *CfgInterface) GetStart() cfg.IDGetter {
	ret := _m.Called()

	var r0 cfg.IDGetter
	if rf, ok := ret.Get(0).(func() cfg.IDGetter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cfg.IDGetter)
		}
	}

	return r0
}

// GetTransitions provides a mock function with given fields:
func (_m *CfgInterface) GetTransitions() cfg.TransitionRegistryInterface {
	ret := _m.Called()

	var r0 cfg.TransitionRegistryInterface
	if rf, ok := ret.Get(0).(func() cfg.TransitionRegistryInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cfg.TransitionRegistryInterface)
		}
	}

	return r0
}
